{{- if .Values.alloy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "specregistry.fullname" . }}-alloy-secrets
  labels:
    {{- include "specregistry.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.alloy.remoteWrite.url }}
  GRAFANA_REMOTE_WRITE_URL: {{ .Values.alloy.remoteWrite.url | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.alloy.remoteWrite.username }}
  GRAFANA_REMOTE_WRITE_USERNAME: {{ .Values.alloy.remoteWrite.username | toString | b64enc | quote }}
  {{- end }}
  {{- if .Values.alloy.remoteWrite.password }}
  GRAFANA_REMOTE_WRITE_PASSWORD: {{ .Values.alloy.remoteWrite.password | toString | b64enc | quote }}
  {{- end }}
{{- end }}
