apiVersion: v1
kind: Secret
metadata:
  name: {{ include "specregistry.fullname" . }}-secrets
  labels:
    {{- include "specregistry.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{- if ne (toString $val) "" }}
  {{ $key }}: {{ $val | toString | b64enc | quote }}
  {{- end }}
  {{- end }}
