import crypto from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { FastifyInstance } from "fastify";
import AdmZip from "adm-zip";
import { buildApp } from "../src/app.js";
import { createDb } from "../src/db.js";
import { seed, SPECREGISTRY_OPERATING_BASELINE_FILENAMES } from "../src/seed.js";
import { assertSecurePosture, findUser, verifyPassword } from "../src/lib/auth.js";
import { buildAdminTestApp } from "./helpers.js";

let app: FastifyInstance;

beforeEach(async () => {
  const db = createDb(":memory:");
  seed(db);
  app = await buildAdminTestApp(db);
});

afterEach(async () => {
  await app.close();
  vi.unstubAllGlobals();
  delete process.env.GITHUB_WEBHOOK_SECRET;
  delete process.env.SLACK_SIGNING_SECRET;
  delete process.env.LDAP_URL;
  delete process.env.LDAP_DEFAULT_ROLE;
  delete process.env.SPECREG_PUBLIC_URL;
  delete process.env.SPECREG_AUTH;
  delete process.env.SPECREG_ADMIN_PASSWORD;
});

async function getJson(target: FastifyInstance, url: string) {
  const res = await target.inject({ method: "GET", url });
  expect(res.statusCode).toBe(200);
  return res.json();
}

async function findSpec(filename: string, typeName: string) {
  const specs = await getJson(app, "/api/v1/specs");
  return specs.find((s: any) => s.filename === filename && s.project_type_name === typeName);
}

async function submitCr(specId: string, content: string, delta = "minor") {
  const res = await app.inject({
    method: "POST",
    url: "/api/v1/specs/review",
    payload: { spec_id: specId, proposed_content: content, version_delta: delta, proposed_by: "joel" },
  });
  expect(res.statusCode).toBe(201);
  return res.json();
}

describe("spec compiler", () => {
  it("renders the governed set into agent context files", async () => {
    const res = await getJson(app, "/api/v1/specs/Acme%20Edge%20Device/compile?target=agents");
    expect(res.target_filename).toBe("AGENTS.md");
    expect(res.content).toContain("<!-- generated by SpecRegistry");
    expect(res.content).toContain("Acme Edge Device — Governed Specifications");
    expect(res.content).toContain("## SpecRegistry Operating Rules");
    expect(res.content).toContain("Prefer MCP when available.");
    expect(res.content).toContain("Treat spec drift as a blocker.");
    expect(res.content).toContain("## Agent Decision Gate");
    expect(res.content).toContain("clear, complete, consistent, and current");
    expect(res.content).toContain("Use `contradiction` when the Consistent gate fails.");
    expect(res.content).toContain("# Global Security Standards");
    expect(res.content).toContain("# Acme Edge Device — Design Specification");
    expect(res.specs.length).toBe(5 + SPECREGISTRY_OPERATING_BASELINE_FILENAMES.length);

    const cursor = await getJson(app, "/api/v1/specs/Web%20App%20Standard/compile?target=cursor");
    expect(cursor.target_filename).toBe(".cursorrules");
    expect(cursor.content).toContain("## SpecRegistry Operating Rules");
    expect(cursor.content).toContain("## Agent Decision Gate");
  });
});

describe("signed bundles", () => {
  it("produces a manifest whose hashes and ed25519 signature verify", async () => {
    const res = await app.inject({ method: "GET", url: "/api/v1/specs/Acme%20Firmware/download" });
    const zip = new AdmZip(res.rawPayload);
    const manifest = JSON.parse(zip.readAsText(".specregistry.json"));
    expect(manifest.signature_alg).toBe("ed25519");

    for (const entry of manifest.specs) {
      const actual = crypto.createHash("sha256").update(zip.readAsText(entry.filename), "utf8").digest("hex");
      expect(actual).toBe(entry.sha256);
    }

    const { public_key } = await getJson(app, "/api/v1/meta/public-key");
    const { signature, signature_alg: _a, ...payload } = manifest;
    const ok = crypto.verify(
      null,
      Buffer.from(JSON.stringify(payload), "utf8"),
      crypto.createPublicKey(public_key),
      Buffer.from(signature, "base64")
    );
    expect(ok).toBe(true);

    // Tampering must break verification
    payload.specs[0].sha256 = "0".repeat(64);
    const tampered = crypto.verify(
      null,
      Buffer.from(JSON.stringify(payload), "utf8"),
      crypto.createPublicKey(public_key),
      Buffer.from(signature, "base64")
    );
    expect(tampered).toBe(false);
  });
});

describe("channels", () => {
  it("beta approval leaves the stable head untouched; promote applies it", async () => {
    const spec = await findSpec("DESIGN.md", "Web App Standard");
    const cr = await submitCr(
      spec.id,
      "# Web App Standard — Design Specification\n\n## System Architecture\nBETA\n\n## Design Patterns\nx\n\n## Data Flow\nx\n"
    );
    const approved = await app.inject({
      method: "POST",
      url: `/api/v1/reviews/${cr.id}/approve`,
      payload: { reviewed_by: "r", channel: "beta" },
    });
    expect(approved.json().resulting_version).toBe("1.1.0-beta.1");

    const head = await getJson(app, `/api/v1/specs/${spec.id}`);
    expect(head.current_version).toBe("1.0.0");
    expect(head.content).not.toContain("BETA");
    expect(head.versions.find((v: any) => v.version === "1.1.0-beta.1").channel).toBe("beta");

    // Beta channel download overlays the beta content
    const dl = await app.inject({ method: "GET", url: "/api/v1/specs/Web%20App%20Standard/download?channel=beta" });
    const zip = new AdmZip(dl.rawPayload);
    expect(zip.readAsText("DESIGN.md")).toContain("BETA");

    const promoted = await app.inject({
      method: "POST",
      url: `/api/v1/specs/${spec.id}/promote`,
      payload: { version: "1.1.0-beta.1", promoted_by: "release-mgr" },
    });
    expect(promoted.statusCode).toBe(200);
    expect(promoted.json().current_version).toBe("1.1.0");
    expect(promoted.json().content).toContain("BETA");
  });
});

describe("approval policies", () => {
  it("keeps a review pending until the configured approval count is met", async () => {
    const types = await getJson(app, "/api/v1/project-types");
    const edge = types.find((t: any) => t.name === "Acme Edge Device");
    const policy = await app.inject({
      method: "POST",
      url: "/api/v1/approval-policies",
      payload: { project_type_id: edge.id, filename_glob: "API.md", min_approvals: 2 },
    });
    expect(policy.statusCode).toBe(201);

    const spec = await findSpec("API.md", "Acme Edge Device");
    const cr = await submitCr(spec.id, "# API v2\n", "patch");

    const first = await app.inject({
      method: "POST",
      url: `/api/v1/reviews/${cr.id}/approve`,
      payload: { reviewed_by: "reviewer-1" },
    });
    expect(first.statusCode).toBe(200);
    expect(first.json().status).toBe("pending");
    expect(first.json().approval_count).toBe(1);
    expect(first.json().required_approvals).toBe(2);

    const detail = await getJson(app, `/api/v1/reviews/${cr.id}`);
    expect(detail.approvals).toEqual([{ reviewer: "reviewer-1", created_at: expect.any(String) }]);
    expect(detail.approval_policy.filename_glob).toBe("API.md");

    const stillPending = await getJson(app, `/api/v1/specs/${spec.id}`);
    expect(stillPending.status).toBe("pending_review");
    expect(stillPending.current_version).toBe("1.0.0");

    const second = await app.inject({
      method: "POST",
      url: `/api/v1/reviews/${cr.id}/approve`,
      payload: { reviewed_by: "reviewer-2" },
    });
    expect(second.statusCode).toBe(200);
    expect(second.json().status).toBe("approved");

    const updated = await getJson(app, `/api/v1/specs/${spec.id}`);
    expect(updated.status).toBe("published");
    expect(updated.current_version).toBe("1.0.1");

    const audit = await getJson(app, "/api/v1/audit-log");
    expect(audit.some((row: any) => row.action === "approval_policy.created")).toBe(true);
    expect(audit.some((row: any) => row.action === "review.approval_recorded")).toBe(true);
    expect(audit.some((row: any) => row.action === "review.published")).toBe(true);
  });
});

describe("review SLA and contradiction checks", () => {
  it("summarizes pending review SLA age and remaining approvals", async () => {
    const spec = await findSpec("API.md", "Acme Edge Device");
    const cr = await submitCr(spec.id, "# API SLA check\n", "patch");
    app.db
      .prepare("UPDATE change_requests SET created_at = ? WHERE id = ?")
      .run(new Date(Date.now() - 80 * 3600 * 1000).toISOString(), cr.id);

    const sla = await getJson(app, "/api/v1/reviews/sla?warn_hours=24&breach_hours=72");
    expect(sla.pending_count).toBeGreaterThanOrEqual(1);
    expect(sla.breached_count).toBeGreaterThanOrEqual(1);
    const row = sla.queue.find((item: any) => item.id === cr.id);
    expect(row.sla_status).toBe("breached");
    expect(row.remaining_approvals).toBe(1);
  });

  it("records possible cross-spec contradictions on change requests", async () => {
    const global = await findSpec("GLOBAL_SECURITY.md", "Global");
    const globalDetail = await getJson(app, `/api/v1/specs/${global.id}`);
    expect(globalDetail.content).toContain("TLS");

    const spec = await findSpec("API.md", "Acme Edge Device");
    const cr = await submitCr(
      spec.id,
      `${spec.filename}\n\n## Transport\nNetwork services must not default to TLS 1.2+ and deny-by-default firewall rules.\n`,
      "minor"
    );
    const detail = await getJson(app, `/api/v1/reviews/${cr.id}`);
    const contradictions = JSON.parse(detail.contradictions);
    expect(contradictions.ok).toBe(false);
    expect(contradictions.findings[0].conflicting_filename).toBe("GLOBAL_SECURITY.md");
    expect(contradictions.findings[0].proposed_anchor).toBe("transport");
  });
});

describe("drift severity & pins", () => {
  it("classifies drift and flags versions outside the caret pin", async () => {
    const spec = await findSpec("STRUCTURE.md", "Acme Firmware");
    const cr = await submitCr(spec.id, "# rewritten\n", "major");
    await app.inject({ method: "POST", url: `/api/v1/reviews/${cr.id}/approve`, payload: { reviewed_by: "r" } });

    const res = await app.inject({
      method: "POST",
      url: "/api/v1/cli/sync-check",
      payload: {
        project_type: "Acme Firmware",
        specs: [{ filename: "STRUCTURE.md", version: "1.0.0", pin: "^1.0.0" }],
      },
    });
    const outdated = res.json().outdated[0];
    expect(outdated.severity).toBe("major");
    expect(outdated.within_pin).toBe(false);
  });
});

describe("auth & roles", () => {
  it("login works, authRequired blocks anonymous, and roles gate routes", async () => {
    const db = createDb(":memory:");
    seed(db);
    const secured = await buildApp(db, { authRequired: true });
    try {
      const anonymous = await secured.inject({ method: "GET", url: "/api/v1/specs" });
      expect(anonymous.statusCode).toBe(401);

      const metrics = await secured.inject({ method: "GET", url: "/metrics" });
      expect(metrics.statusCode).toBe(200);
      expect(metrics.body).toContain("specregistry_info");

      const login = await secured.inject({
        method: "POST",
        url: "/api/v1/auth/login",
        payload: { username: "admin", password: "admin" },
      });
      expect(login.statusCode).toBe(200);
      const adminToken = login.json().token;
      const adminHeaders = { authorization: `Bearer ${adminToken}` };

      const me = await secured.inject({ method: "GET", url: "/api/v1/auth/me", headers: adminHeaders });
      expect(me.json().role).toBe("admin");

      // Create an author and get a key for them
      await secured.inject({
        method: "POST",
        url: "/api/v1/auth/users",
        headers: adminHeaders,
        payload: { username: "alice", role: "author", password: "pw" },
      });
      const aliceKey = (
        await secured.inject({
          method: "POST",
          url: "/api/v1/auth/api-keys",
          headers: adminHeaders,
          payload: { username: "alice" },
        })
      ).json().token;
      const aliceHeaders = { authorization: `Bearer ${aliceKey}` };

      const specs = await secured.inject({ method: "GET", url: "/api/v1/specs", headers: aliceHeaders });
      expect(specs.statusCode).toBe(200);
      const spec = specs.json()[0];

      const cr = (
        await secured.inject({
          method: "POST",
          url: "/api/v1/specs/review",
          headers: aliceHeaders,
          payload: { spec_id: spec.id, proposed_content: "# new\n", version_delta: "patch", proposed_by: "alice" },
        })
      ).json();

      // Author cannot approve; admin can
      const denied = await secured.inject({
        method: "POST",
        url: `/api/v1/reviews/${cr.id}/approve`,
        headers: aliceHeaders,
        payload: { reviewed_by: "alice" },
      });
      expect(denied.statusCode).toBe(403);

      const blockedAdminRoute = await secured.inject({
        method: "POST",
        url: "/api/v1/webhooks",
        headers: aliceHeaders,
        payload: { url: "https://x", events: [] },
      });
      expect(blockedAdminRoute.statusCode).toBe(403);

      const readableSkills = await secured.inject({ method: "GET", url: "/api/v1/skills", headers: aliceHeaders });
      expect(readableSkills.statusCode).toBe(200);
      const blockedDisabledSkills = await secured.inject({ method: "GET", url: "/api/v1/skills?include_disabled=true", headers: aliceHeaders });
      expect(blockedDisabledSkills.statusCode).toBe(403);
      const blockedSkillRegistration = await secured.inject({
        method: "POST",
        url: "/api/v1/skills",
        headers: aliceHeaders,
        payload: { name: "Unsafe registration", description: "Should fail.", instructions: "Do nothing." },
      });
      expect(blockedSkillRegistration.statusCode).toBe(403);

      const blockedUserList = await secured.inject({
        method: "GET",
        url: "/api/v1/auth/users",
        headers: aliceHeaders,
      });
      expect(blockedUserList.statusCode).toBe(403);

      const listedUsers = await secured.inject({
        method: "GET",
        url: "/api/v1/auth/users",
        headers: adminHeaders,
      });
      expect(listedUsers.statusCode).toBe(200);
      expect(listedUsers.json().some((u: any) => u.username === "alice")).toBe(true);

      const listedKeys = await secured.inject({
        method: "GET",
        url: "/api/v1/auth/api-keys",
        headers: adminHeaders,
      });
      expect(listedKeys.statusCode).toBe(200);
      const aliceKeyRow = listedKeys.json().find((k: any) => k.username === "alice");
      expect(aliceKeyRow.name).toBe("api key");

      const revoked = await secured.inject({
        method: "DELETE",
        url: `/api/v1/auth/api-keys/${aliceKeyRow.id}`,
        headers: adminHeaders,
      });
      expect(revoked.statusCode).toBe(204);

      const revokedToken = await secured.inject({
        method: "GET",
        url: "/api/v1/specs",
        headers: aliceHeaders,
      });
      expect(revokedToken.statusCode).toBe(401);

      const approved = await secured.inject({
        method: "POST",
        url: `/api/v1/reviews/${cr.id}/approve`,
        headers: adminHeaders,
        payload: { reviewed_by: "admin" },
      });
      expect(approved.statusCode).toBe(200);

      const badToken = await secured.inject({
        method: "GET",
        url: "/api/v1/specs",
        headers: { authorization: "Bearer sreg_bogus" },
      });
      expect(badToken.statusCode).toBe(401);
    } finally {
      await secured.close();
    }
  });

  it("requires authentication for policy-protected routes even when global auth is optional", async () => {
    const db = createDb(":memory:");
    seed(db);
    const optionalAuth = await buildApp(db, { authRequired: false });
    try {
      const publicSpecs = await optionalAuth.inject({ method: "GET", url: "/api/v1/specs" });
      expect(publicSpecs.statusCode).toBe(200);

      const protectedWrite = await optionalAuth.inject({
        method: "POST",
        url: "/api/v1/webhooks",
        payload: { url: "https://hooks.example.com/specs", events: [] },
      });
      expect(protectedWrite.statusCode).toBe(401);
    } finally {
      await optionalAuth.close();
    }
  });

  it("enforces per-project-type required reviewers", async () => {
    const types = await getJson(app, "/api/v1/project-types");
    const web = types.find((t: any) => t.name === "Web App Standard");
    await app.inject({
      method: "PUT",
      url: `/api/v1/project-types/${web.id}`,
      payload: { required_reviewers: ["security-team"] },
    });

    const spec = await findSpec("STRUCTURE.md", "Web App Standard");
    const cr = await submitCr(spec.id, "# v2\n", "patch");
    await app.inject({
      method: "POST",
      url: "/api/v1/auth/users",
      payload: { username: "random-person", role: "reviewer", password: "pw" },
    });
    await app.inject({
      method: "POST",
      url: "/api/v1/auth/users",
      payload: { username: "security-team", role: "reviewer", password: "pw" },
    });
    const randomToken = (
      await app.inject({ method: "POST", url: "/api/v1/auth/api-keys", payload: { username: "random-person" } })
    ).json().token;
    const securityToken = (
      await app.inject({ method: "POST", url: "/api/v1/auth/api-keys", payload: { username: "security-team" } })
    ).json().token;

    const wrongReviewer = await app.inject({
      method: "POST",
      url: `/api/v1/reviews/${cr.id}/approve`,
      headers: { authorization: `Bearer ${randomToken}` },
      payload: { reviewed_by: "random-person" },
    });
    expect(wrongReviewer.statusCode).toBe(403);

    const rightReviewer = await app.inject({
      method: "POST",
      url: `/api/v1/reviews/${cr.id}/approve`,
      headers: { authorization: `Bearer ${securityToken}` },
      payload: { reviewed_by: "security-team" },
    });
    expect(rightReviewer.statusCode).toBe(200);
  });
});

describe("LDAP settings", () => {
  it("persists config, masks bind password, and previews role mapping", async () => {
    const saved = await app.inject({
      method: "PUT",
      url: "/api/v1/ldap/config",
      payload: {
        url: "ldap://directory.example.com",
        bind_user: "cn=reader,dc=example,dc=com",
        bind_password: "secret",
        search_base: "ou=people,dc=example,dc=com",
        search_filter: "(uid={username})",
        admin_group: "cn=admins,dc=example,dc=com",
        reviewer_group: "cn=reviewers,dc=example,dc=com",
        default_role: "agent",
      },
    });
    expect(saved.statusCode).toBe(200);
    expect(saved.json().enabled).toBe(true);
    expect(saved.json()).not.toHaveProperty("bind_password");
    expect(saved.json().has_bind_password).toBe(true);

    const loaded = await getJson(app, "/api/v1/ldap/config");
    expect(loaded.url).toBe("ldap://directory.example.com");
    expect(loaded.default_role).toBe("agent");

    const reviewer = await app.inject({
      method: "POST",
      url: "/api/v1/ldap/role-preview",
      payload: { groups: ["cn=reviewers,dc=example,dc=com"] },
    });
    expect(reviewer.statusCode).toBe(200);
    expect(reviewer.json().role).toBe("reviewer");

    const fallback = await app.inject({
      method: "POST",
      url: "/api/v1/ldap/role-preview",
      payload: { groups: ["cn=unknown,dc=example,dc=com"] },
    });
    expect(fallback.json().role).toBe("agent");
  });
});

describe("agent MCP guide", () => {
  it("returns a feedable guide and matching MCP config for a project type", async () => {
    process.env.SPECREG_PUBLIC_URL = "https://specreg.example.com";
    const guide = await getJson(app, "/api/v1/ai/mcp-guide/Acme%20Edge%20Device");
    expect(guide.filename).toBe("SPECREGISTRY_MCP_SKILL.md");
    expect(guide.project_type).toBe("Acme Edge Device");
    expect(guide.content).toContain("SpecRegistry MCP Skill");
    expect(guide.content).toContain("get_specs");
    expect(guide.content).toContain("pre-implementation gate");
    expect(guide.content).toContain("check_compliance");
    expect(guide.content).toContain("SPECREG_TOKEN");
    expect(guide.mcp_config.mcpServers.specregistry.command).toBe("specreg");
    expect(guide.mcp_config.mcpServers.specregistry.args).toEqual(["mcp"]);
    expect(guide.mcp_config.mcpServers.specregistry.env.SPECREG_SERVER).toBe("https://specreg.example.com");
    expect(guide.mcp_config.mcpServers.specregistry.env.SPECREG_PROJECT_TYPE).toBe("Acme Edge Device");
  });

  it("returns a downloadable agent pack with generated files and MCP setup", async () => {
    process.env.SPECREG_PUBLIC_URL = "https://specreg.example.com";
    const res = await app.inject({ method: "GET", url: "/api/v1/specs/Acme%20Edge%20Device/agent-pack" });
    expect(res.statusCode).toBe(200);
    const zip = new AdmZip(res.rawPayload);
    const names = zip.getEntries().map((e) => e.entryName);
    expect(names).toContain("CLAUDE.md");
    expect(names).toContain("AGENTS.md");
    expect(names).toContain(".cursorrules");
    expect(names).toContain(".mcp.json");
    expect(names).toContain("SPECREGISTRY_MCP_SKILL.md");
    expect(names).toContain(".spec/skills/manifest.json");
    expect(names).toContain(".spec/skills/load-governed-specs/SKILL.md");
    expect(zip.readAsText("SPECREGISTRY_MCP_SKILL.md")).toContain("report_spec_feedback");
    expect(zip.readAsText("SPECREGISTRY_MCP_SKILL.md")).toContain("specreg mcp");
    expect(zip.readAsText("SPECREGISTRY_MCP_SKILL.md")).toContain("SPECREG_TOKEN");
    expect(zip.readAsText(".spec/skills/load-governed-specs/SKILL.md")).toContain("Safety Boundary");
    const mcp = JSON.parse(zip.readAsText(".mcp.json"));
    expect(mcp.mcpServers.specregistry.command).toBe("specreg");
    expect(mcp.mcpServers.specregistry.args).toEqual(["mcp"]);
    expect(mcp.mcpServers.specregistry.env.SPECREG_SERVER).toBe("https://specreg.example.com");
    expect(mcp.mcpServers.specregistry.env.SPECREG_PROJECT_TYPE).toBe("Acme Edge Device");
  });
});

describe("chat integrations", () => {
  it("sends gchat-format webhook payloads and Slack payloads with approval buttons", async () => {
    await app.inject({
      method: "POST",
      url: "/api/v1/webhooks",
      payload: { url: "https://chat.googleapis.com/v1/spaces/x", events: [], format: "gchat" },
    });
    await app.inject({
      method: "POST",
      url: "/api/v1/webhooks",
      payload: { url: "https://hooks.slack.com/services/x", events: [], format: "slack" },
    });
    const fetchMock = vi.fn().mockResolvedValue(new Response("ok"));
    vi.stubGlobal("fetch", fetchMock);

    const spec = await findSpec("API.md", "Acme Edge Device");
    await submitCr(spec.id, "# v2\n", "patch");

    expect(fetchMock).toHaveBeenCalledTimes(2);
    const bodies = fetchMock.mock.calls.map((c) => JSON.parse(c[1].body));
    const gchat = bodies.find((b) => !b.blocks);
    const slack = bodies.find((b) => b.blocks);
    expect(gchat.text).toContain("review.submitted");
    expect(slack.blocks[1].elements[0].value).toMatch(/^approve:/);
  });

  it("approves a change request from a signed Slack action", async () => {
    process.env.SLACK_SIGNING_SECRET = "slack-secret";
    const spec = await findSpec("DESIGN.md", "Acme Firmware");
    const cr = await submitCr(spec.id, "# from slack\n", "patch");

    const payload = JSON.stringify({
      actions: [{ value: `approve:${cr.id}` }],
      user: { username: "joel" },
    });
    const body = `payload=${encodeURIComponent(payload)}`;
    const ts = String(Math.floor(Date.now() / 1000));
    const signature =
      "v0=" + crypto.createHmac("sha256", "slack-secret").update(`v0:${ts}:${body}`).digest("hex");

    const res = await app.inject({
      method: "POST",
      url: "/api/v1/integrations/slack/actions",
      headers: {
        "content-type": "application/x-www-form-urlencoded",
        "x-slack-request-timestamp": ts,
        "x-slack-signature": signature,
      },
      payload: body,
    });
    expect(res.statusCode).toBe(200);
    expect(res.json().text).toContain("approved");

    const updated = await getJson(app, `/api/v1/specs/${spec.id}`);
    expect(updated.current_version).toBe("1.0.1");

    const forged = await app.inject({
      method: "POST",
      url: "/api/v1/integrations/slack/actions",
      headers: {
        "content-type": "application/x-www-form-urlencoded",
        "x-slack-request-timestamp": ts,
        "x-slack-signature": "v0=deadbeef",
      },
      payload: body,
    });
    expect(forged.statusCode).toBe(401);
  });
});

describe("inbound GitHub sync", () => {
  it("verifies the HMAC and opens a change request for edited spec files", async () => {
    process.env.GITHUB_WEBHOOK_SECRET = "gh-secret";
    const types = await getJson(app, "/api/v1/project-types");
    const edge = types.find((t: any) => t.name === "Acme Edge Device");
    await app.inject({
      method: "POST",
      url: "/api/v1/subscriptions",
      payload: { project_type_id: edge.id, repo: "joeldg/edge-repo", branch: "main", base_path: "specs" },
    });

    const newContent = "# Acme Edge Device — Design Specification\n\nEdited in the repo.\n";
    vi.stubGlobal(
      "fetch",
      vi.fn().mockResolvedValue(new Response(newContent, { status: 200 }))
    );

    const event = JSON.stringify({
      ref: "refs/heads/main",
      repository: { full_name: "joeldg/edge-repo" },
      pusher: { name: "joel" },
      head_commit: { id: "abc123" },
      commits: [{ added: [], modified: ["specs/DESIGN.md", "src/main.c"] }],
    });
    const signature = "sha256=" + crypto.createHmac("sha256", "gh-secret").update(event).digest("hex");

    const forged = await app.inject({
      method: "POST",
      url: "/api/v1/integrations/github/webhook",
      headers: { "content-type": "application/json", "x-github-event": "push", "x-hub-signature-256": "sha256=bad" },
      payload: event,
    });
    expect(forged.statusCode).toBe(401);

    const res = await app.inject({
      method: "POST",
      url: "/api/v1/integrations/github/webhook",
      headers: {
        "content-type": "application/json",
        "x-github-event": "push",
        "x-hub-signature-256": signature,
      },
      payload: event,
    });
    expect(res.statusCode).toBe(200);
    expect(res.json().change_requests.length).toBe(1);

    const reviews = await getJson(app, "/api/v1/reviews?status=pending");
    expect(reviews[0].proposed_by).toContain("joel (via joeldg/edge-repo)");
    expect(reviews[0].filename).toBe("DESIGN.md");
    // Removing sections suggests a major bump, picked automatically for inbound changes
    expect(JSON.parse(reviews[0].compatibility).suggested_delta).toBe("major");
  });
});

describe("AI endpoints without a key", () => {
  it("efficacy and audit return 503 when no LLM provider is configured", async () => {
    const previous = process.env.ANTHROPIC_API_KEY;
    const previousProvider = process.env.LLM_PROVIDER;
    const previousBase = process.env.LLM_BASE_URL;
    const previousKey = process.env.LLM_API_KEY;
    delete process.env.ANTHROPIC_API_KEY;
    delete process.env.LLM_PROVIDER;
    delete process.env.LLM_BASE_URL;
    delete process.env.LLM_API_KEY;
    try {
      const spec = await findSpec("API.md", "Acme Edge Device");
      const efficacy = await app.inject({
        method: "POST",
        url: "/api/v1/ai/efficacy",
        payload: { spec_id: spec.id, task_prompt: "Add an endpoint" },
      });
      expect(efficacy.statusCode).toBe(503);
      const audit = await app.inject({
        method: "POST",
        url: "/api/v1/ai/audit",
        payload: { project_type: "Acme Edge Device", tree: "x/", files: [] },
      });
      expect(audit.statusCode).toBe(503);
    } finally {
      if (previous !== undefined) process.env.ANTHROPIC_API_KEY = previous;
      if (previousProvider !== undefined) process.env.LLM_PROVIDER = previousProvider;
      if (previousBase !== undefined) process.env.LLM_BASE_URL = previousBase;
      if (previousKey !== undefined) process.env.LLM_API_KEY = previousKey;
    }
  });
});

describe("agent identity, scope, and separation of duties", () => {
  async function enroll(repo: string, projectType = "Web App Standard") {
    const res = await app.inject({
      method: "POST",
      url: "/api/v1/agents/enroll",
      payload: { repo, project_type: projectType },
    });
    expect(res.statusCode).toBe(201);
    return res.json() as { token: string; username: string; role: string };
  }
  function asAgent(token: string) {
    return { authorization: `Bearer ${token}` };
  }

  it("enrolls an agent-role identity bound to the repo", async () => {
    const agent = await enroll("github.com/acme/game");
    expect(agent.role).toBe("agent");
    expect(agent.username).toBe("agent:github.com/acme/game");
    expect(agent.token).toMatch(/^sreg_/);
  });

  it("lets an agent create + publish its own project-scoped spec but not a governed one", async () => {
    const repo = "github.com/acme/game";
    const types = await getJson(app, "/api/v1/project-types");
    const web = types.find((t: any) => t.name === "Web App Standard");
    // register the repo as a project consumer
    const project = (
      await app.inject({
        method: "POST",
        url: "/api/v1/cli/manifest-report",
        payload: { repo, project_type: "Web App Standard", specs: [] },
      })
    ).json();
    const agent = await enroll(repo);

    // project-scoped create + publish: allowed
    const created = await app.inject({
      method: "POST",
      url: "/api/v1/specs",
      headers: asAgent(agent.token),
      payload: {
        project_type_id: web.id,
        project_id: project.project_id,
        filename: "STYLE_NOTES.md",
        content: "# Style notes\n\n## Scope\nlocal\n",
        updated_by: "ignored",
      },
    });
    expect(created.statusCode).toBe(201);
    expect(created.json().updated_by).toBe(agent.username); // identity forced
    const published = await app.inject({
      method: "POST",
      url: `/api/v1/specs/${created.json().id}/publish`,
      headers: asAgent(agent.token),
      payload: {},
    });
    expect(published.statusCode).toBe(200);
    expect(published.json().status).toBe("published");

    // governed (no project_id) create: forbidden
    const governed = await app.inject({
      method: "POST",
      url: "/api/v1/specs",
      headers: asAgent(agent.token),
      payload: { project_type_id: web.id, filename: "DESIGN.md", content: "x", updated_by: "a" },
    });
    expect(governed.statusCode).toBe(403);
  });

  it("forbids an agent from approving any change request", async () => {
    const spec = await findSpec("DESIGN.md", "Acme Edge Device");
    const cr = await submitCr(spec.id, "# proposed by human\n", "patch");
    const agent = await enroll("github.com/acme/other");
    const res = await app.inject({
      method: "POST",
      url: `/api/v1/reviews/${cr.id}/approve`,
      headers: asAgent(agent.token),
      payload: { reviewed_by: agent.username },
    });
    expect(res.statusCode).toBe(403);
  });

  it("blocks a reviewer from approving their own proposal (separation of duties)", async () => {
    // create two reviewers with tokens
    await app.inject({ method: "POST", url: "/api/v1/auth/users", payload: { username: "rev1", role: "reviewer", password: "x" } });
    await app.inject({ method: "POST", url: "/api/v1/auth/users", payload: { username: "rev2", role: "reviewer", password: "x" } });
    const rev1 = (await app.inject({ method: "POST", url: "/api/v1/auth/api-keys", payload: { username: "rev1" } })).json().token;
    const rev2 = (await app.inject({ method: "POST", url: "/api/v1/auth/api-keys", payload: { username: "rev2" } })).json().token;

    const spec = await findSpec("STRUCTURE.md", "Acme Edge Device");
    const cr = (
      await app.inject({
        method: "POST",
        url: "/api/v1/specs/review",
        payload: { spec_id: spec.id, proposed_content: "# rev1 change\n", version_delta: "patch", proposed_by: "rev1" },
      })
    ).json();

    const selfApprove = await app.inject({
      method: "POST",
      url: `/api/v1/reviews/${cr.id}/approve`,
      headers: { authorization: `Bearer ${rev1}` },
      payload: { reviewed_by: "rev1" },
    });
    expect(selfApprove.statusCode).toBe(403);

    const otherApprove = await app.inject({
      method: "POST",
      url: `/api/v1/reviews/${cr.id}/approve`,
      headers: { authorization: `Bearer ${rev2}` },
      payload: { reviewed_by: "rev2" },
    });
    expect(otherApprove.statusCode).toBe(200);
  });

  it("blocks admin self-approval unless explicitly enabled", async () => {
    const spec = await findSpec("API.md", "Acme Edge Device");
    const cr = (
      await app.inject({
        method: "POST",
        url: "/api/v1/specs/review",
        payload: { spec_id: spec.id, proposed_content: "# admin change\n", version_delta: "patch", proposed_by: "admin" },
      })
    ).json();

    const blocked = await app.inject({
      method: "POST",
      url: `/api/v1/reviews/${cr.id}/approve`,
      payload: { reviewed_by: "admin" },
    });
    expect(blocked.statusCode).toBe(403);

    process.env.SPECREG_ALLOW_ADMIN_SELF_APPROVE = "true";
    try {
      const allowed = await app.inject({
        method: "POST",
        url: `/api/v1/reviews/${cr.id}/approve`,
        payload: { reviewed_by: "admin" },
      });
      expect(allowed.statusCode).toBe(200);
    } finally {
      delete process.env.SPECREG_ALLOW_ADMIN_SELF_APPROVE;
    }
  });
});

describe("secured posture", () => {
  it("refuses to run with the default admin password when auth is required", () => {
    delete process.env.SPECREG_AUTH; // seed with dev default so admin password is "admin"
    delete process.env.SPECREG_ADMIN_PASSWORD;
    const db = createDb(":memory:");
    seed(db);
    expect(() => assertSecurePosture(db, { authRequired: true })).toThrow(/default password/i);
    // Dev mode tolerates it.
    expect(() => assertSecurePosture(db, { authRequired: false })).not.toThrow();
  });

  it("passes the guard when SPECREG_ADMIN_PASSWORD is set", () => {
    process.env.SPECREG_ADMIN_PASSWORD = "a-strong-passphrase";
    const db = createDb(":memory:");
    seed(db);
    expect(() => assertSecurePosture(db, { authRequired: true })).not.toThrow();
    const admin = findUser(db, "admin");
    expect(verifyPassword("a-strong-passphrase", admin!.password_hash!)).toBe(true);
    expect(verifyPassword("admin", admin!.password_hash!)).toBe(false);
  });

  it("auto-generates a non-default admin password in secured fresh-seed", () => {
    process.env.SPECREG_AUTH = "required";
    delete process.env.SPECREG_ADMIN_PASSWORD;
    const db = createDb(":memory:");
    seed(db);
    const admin = findUser(db, "admin");
    expect(admin).toBeTruthy();
    expect(verifyPassword("admin", admin!.password_hash!)).toBe(false);
    expect(() => assertSecurePosture(db, { authRequired: true })).not.toThrow();
  });
});
