import type { ProjectType, Spec } from "@specregistry/shared";
import type { Db } from "../db.js";
import { now } from "../db.js";

export type CompileTarget = "claude" | "agents" | "cursor";

export const TARGET_FILENAMES: Record<CompileTarget, string> = {
  claude: "CLAUDE.md",
  agents: "AGENTS.md",
  cursor: ".cursorrules",
};

export const GENERATED_MARKER = "<!-- generated by SpecRegistry";

interface BundleSpec extends Spec {
  project_type_scope: string;
  project_name?: string | null;
}

/** The published spec set for a project type or concrete project (global -> type -> project), with channel overlay. */
export function bundleSpecs(db: Db, projectTypeId: string, channel = "stable", projectId?: string): BundleSpec[] {
  const rows = db
    .prepare(
      `SELECT s.*, pt.scope AS project_type_scope, rc.repo AS project_name FROM specs s
       JOIN project_types pt ON pt.id = s.project_type_id
       LEFT JOIN repo_consumers rc ON rc.id = s.project_id
       WHERE s.status != 'draft'
         AND (
          (s.project_id IS NULL AND (pt.id = ? OR pt.scope = 'global'))
          OR (? IS NOT NULL AND s.project_id = ?)
         )
       ORDER BY
         CASE WHEN s.project_id IS NOT NULL THEN 2 WHEN pt.scope = 'global' THEN 0 ELSE 1 END,
         s.filename`
    )
    .all(projectTypeId, projectId ?? null, projectId ?? null) as BundleSpec[];
  const byFilename = new Map<string, BundleSpec>();
  for (const spec of rows) byFilename.set(spec.filename, spec);
  const specs = [...byFilename.values()];
  if (channel !== "stable") {
    for (const spec of specs) {
      const beta = db
        .prepare(
          `SELECT version, content FROM spec_versions
           WHERE spec_id = ? AND channel = ? ORDER BY published_at DESC LIMIT 1`
        )
        .get(spec.id, channel) as { version: string; content: string } | undefined;
      if (beta) {
        spec.current_version = beta.version;
        spec.content = beta.content;
      }
    }
  }
  return specs;
}

/**
 * Render a project type's governed spec set into a single agent context file
 * (CLAUDE.md / AGENTS.md / .cursorrules). The registry stays the source of truth;
 * the output is regenerated by `specreg sync` and must not be hand-edited.
 */
export function compileBundle(
  db: Db,
  projectType: ProjectType,
  target: CompileTarget,
  channel = "stable",
  projectId?: string
): { target_filename: string; content: string; specs: Array<{ filename: string; version: string }> } {
  const specs = bundleSpecs(db, projectType.id, channel, projectId);
  const included = specs.map((s) => ({ filename: s.filename, version: s.current_version }));

  const intro =
    target === "cursor"
      ? "These are the governed engineering rules for this repository. Follow every section below."
      : `This file is compiled from the organization's governed specification registry for the project type **${projectType.name}**. Treat every section as authoritative guidance. If you find a contradiction or ambiguity while working, report it through the SpecRegistry feedback channel (MCP tool \`report_spec_feedback\` or POST /api/v1/ai/feedback) instead of guessing.`;

  const parts: string[] = [
    `${GENERATED_MARKER} — do not edit by hand; run \`specreg sync\` to refresh. -->`,
    "",
    `# ${projectType.name} — Governed Specifications`,
    "",
    intro,
    "",
    `_Compiled ${now()}${channel !== "stable" ? ` · channel: ${channel}` : ""} · ${included
      .map((s) => `${s.filename}@${s.version}`)
      .join(" · ")}_`,
    "",
  ];
  for (const spec of specs) {
    const origin = spec.project_id ? `project:${spec.project_name ?? spec.project_id}` : spec.project_type_scope === "global" ? "global" : projectType.name;
    parts.push("---", "", `<!-- ${spec.filename} v${spec.current_version} (${origin}) -->`, "", spec.content.trim(), "");
  }
  return { target_filename: TARGET_FILENAMES[target], content: parts.join("\n"), specs: included };
}
