import type { ProjectType, Spec } from "@specregistry/shared";
import type { Db } from "../db.js";
import { now } from "../db.js";

export type CompileTarget = "claude" | "agents" | "cursor";

export const TARGET_FILENAMES: Record<CompileTarget, string> = {
  claude: "CLAUDE.md",
  agents: "AGENTS.md",
  cursor: ".cursorrules",
};

export const GENERATED_MARKER = "<!-- generated by SpecRegistry";

interface BundleSpec extends Spec {
  project_type_scope: string;
  project_name?: string | null;
}

const AGENT_DECISION_GATE = `## Agent Decision Gate

Before coding, verify the applicable specs are clear, complete, consistent, and current.

Proceed only when you can state: "For this task, spec <filename>@<version> section <section> requires <behavior>, and the implementation will satisfy it by <specific action/test>."

File SpecRegistry feedback instead of guessing when any gate fails:

| Gate | Proceed when | File feedback when |
| --- | --- | --- |
| Clear | The relevant section gives a single actionable rule, requirement, or acceptance criterion. | The spec is vague, leaves a key decision open, or supports multiple reasonable interpretations. |
| Complete | Inputs, outputs, boundaries, non-goals, failure behavior, and acceptance expectations are sufficient for the change. | Required details are missing, such as status codes, data shape, ownership, security behavior, or test expectations. |
| Consistent | Global, project-type, and project-scoped specs can all be followed at the same time. | Two specs, two sections, or a spec and project override require incompatible behavior. |
| Current | Referenced files, APIs, commands, architecture, and operational assumptions still match the codebase or are explicitly targeted future state. | The spec points to removed APIs, renamed files, obsolete workflows, stale infrastructure, or superseded behavior. |

Feedback type mapping:

- Use \`ambiguity\` when the Clear or Complete gate fails.
- Use \`contradiction\` when the Consistent gate fails.
- Use \`outdated\` when the Current gate fails.

When reporting feedback, include the affected \`spec_id\`, what you were trying to do, the exact unclear/conflicting/outdated guidance, relevant code or spec context, and the decision you needed from the spec.`;

const SPECREGISTRY_OPERATING_RULES = `## SpecRegistry Operating Rules

These rules govern how you use this compiled file with SpecRegistry:

1. Prefer MCP when available. Use the \`specregistry\` MCP server from \`.mcp.json\` to call \`get_specs\`, \`search_specs\`, \`report_spec_feedback\`, and \`get_audit_prompt\`.
2. Load live specs before non-trivial code changes. This compiled file is a bootstrap, but MCP is the live retrieval and feedback channel.
3. Preserve project scope. Ensure MCP is using the configured project type and repo/project identity so global, project-type, and project-scoped specs are all visible.
4. Search before assuming. Use \`search_specs\` for task terms, APIs, filenames, security concerns, failure modes, and acceptance criteria before deciding guidance is missing.
5. Do not edit generated governance files by hand. Refresh \`CLAUDE.md\`, \`AGENTS.md\`, \`.cursorrules\`, and governed \`specs/\` content with \`specreg sync\` or \`specreg compile\`.
6. Treat spec drift as a blocker. If local specs appear stale, ask for or run \`specreg check\` / \`specreg sync\` before relying on them.
7. Report spec problems through SpecRegistry. If guidance is unclear, incomplete, contradictory, or outdated, call \`report_spec_feedback\` instead of guessing.
8. Follow published specs until they change. Feedback and draft fixes do not override the source of truth until a reviewed spec update is published and synced.`;

/** The published spec set for a project type or concrete project (global -> type -> project), with channel overlay. */
export function bundleSpecs(db: Db, projectTypeId: string, channel = "stable", projectId?: string): BundleSpec[] {
  const rows = db
    .prepare(
      `SELECT s.*, pt.scope AS project_type_scope, rc.repo AS project_name FROM specs s
       JOIN project_types pt ON pt.id = s.project_type_id
       LEFT JOIN repo_consumers rc ON rc.id = s.project_id
       WHERE s.status != 'draft'
         AND (
          (s.project_id IS NULL AND (pt.id = ? OR pt.scope = 'global'))
          OR (? IS NOT NULL AND s.project_id = ?)
         )
       ORDER BY
         CASE WHEN s.project_id IS NOT NULL THEN 2 WHEN pt.scope = 'global' THEN 0 ELSE 1 END,
         s.filename`
    )
    .all(projectTypeId, projectId ?? null, projectId ?? null) as BundleSpec[];
  const byFilename = new Map<string, BundleSpec>();
  for (const spec of rows) byFilename.set(spec.filename, spec);
  const specs = [...byFilename.values()];
  if (channel !== "stable") {
    for (const spec of specs) {
      const beta = db
        .prepare(
          `SELECT version, content FROM spec_versions
           WHERE spec_id = ? AND channel = ? ORDER BY published_at DESC LIMIT 1`
        )
        .get(spec.id, channel) as { version: string; content: string } | undefined;
      if (beta) {
        spec.current_version = beta.version;
        spec.content = beta.content;
      }
    }
  }
  return specs;
}

/**
 * Render a project type's governed spec set into a single agent context file
 * (CLAUDE.md / AGENTS.md / .cursorrules). The registry stays the source of truth;
 * the output is regenerated by `specreg sync` and must not be hand-edited.
 */
export function compileBundle(
  db: Db,
  projectType: ProjectType,
  target: CompileTarget,
  channel = "stable",
  projectId?: string
): { target_filename: string; content: string; specs: Array<{ filename: string; version: string }> } {
  const specs = bundleSpecs(db, projectType.id, channel, projectId);
  const included = specs.map((s) => ({ filename: s.filename, version: s.current_version }));

  const intro =
    target === "cursor"
      ? "These are the governed engineering rules for this repository. Follow every section below."
      : `This file is compiled from the organization's governed specification registry for the project type **${projectType.name}**. Treat every section as authoritative guidance. If you find a contradiction or ambiguity while working, report it through the SpecRegistry feedback channel (MCP tool \`report_spec_feedback\` or POST /api/v1/ai/feedback) instead of guessing.`;

  const parts: string[] = [
    `${GENERATED_MARKER} — do not edit by hand; run \`specreg sync\` to refresh. -->`,
    "",
    `# ${projectType.name} — Governed Specifications`,
    "",
    intro,
    "",
    `_Compiled ${now()}${channel !== "stable" ? ` · channel: ${channel}` : ""} · ${included
      .map((s) => `${s.filename}@${s.version}`)
      .join(" · ")}_`,
    "",
    SPECREGISTRY_OPERATING_RULES,
    "",
    AGENT_DECISION_GATE,
    "",
  ];
  for (const spec of specs) {
    const origin = spec.project_id ? `project:${spec.project_name ?? spec.project_id}` : spec.project_type_scope === "global" ? "global" : projectType.name;
    parts.push("---", "", `<!-- ${spec.filename} v${spec.current_version} (${origin}) -->`, "", spec.content.trim(), "");
  }
  return { target_filename: TARGET_FILENAMES[target], content: parts.join("\n"), specs: included };
}
